[build]
  publish = "."
  command = ""

[[headers]]
  for = "/css/*"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/js/*"
  [headers.values]
    Content-Type = "application/javascript"
    [[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Ignorar archivos específicos
[[redirects]]
  from = "/webpage_content_reporter.js"
  to = "/dev/null"
  status = 200
  force = true